# Generated by Django 4.0.4 on 2022-04-18 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('24ba6836-5acb-4e64-961a-b994de8cfb01')),
        ),
        migrations.AddField(
            model_name='review',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('58977b57-8293-4a84-bccc-34ef7bb138a4')),
        ),
    ]
