# Generated by Django 4.0.4 on 2022-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0003_restaurant_image_name_review_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_name',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_name',
            field=models.UUIDField(),
        ),
    ]
