# Generated by Django 4.0.4 on 2022-04-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0006_alter_review_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
