# Generated by Django 4.0.4 on 2022-04-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0005_remove_restaurant_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_name',
            field=models.CharField(max_length=100),
        ),
    ]
